chaosteil/doist

- README.md
- src/api/rest/comment.rs
- src/api/rest/gateway.rs
- src/api/rest/task.rs
- src/api/tree.rs
- src/command.rs
- src/comments/list.rs
- src/comments/mod.rs
- src/lib.rs
- src/tasks/list.rs
- src/tasks/mod.rs
- src/tasks/view.rs
Implemented listing of comments and integrated them together with tasks so task
comments are now viewable. Additionally had some light cleanups around list.
Next up will probably be comment and detail view for projects.
> Enable viewing of task details with comments

- src/api/rest/section.rs
- src/api/rest/task.rs
- src/api/tree.rs
- src/command.rs
- src/comments/list.rs
- src/interactive.rs
- src/lib.rs
- src/projects/filter.rs
- src/projects/mod.rs
- src/projects/view.rs
- src/tasks/close.rs
- src/tasks/edit.rs
- src/tasks/filter.rs
- src/tasks/list.rs
- src/tasks/mod.rs
- src/tasks/view.rs
Implements project view to display details of a project, including project
comments. Has interactive project selection just as with tasks if project is not
specified.
Has some refactoring here and there to keep code reuse to minimum, but probably needs another pass.
> Implement project view

- Cargo.lock
- Cargo.toml
- src/api/rest/gateway.rs
Add an authentication test and update some Cargo dependencies.
> Add authentication test

- src/api/rest/gateway.rs
- src/api/rest/project.rs
- src/api/rest/task.rs
Added more tests in gateway about projects, and finished up the task gateway
tests. Additionally made the task url type an actual url.
> Add tests in gateway for projects

- .github/workflows/ci.yml
Add cargo formatting so Rust code is always properly formatted when checked in.
> Add cargo fmt workflow

- src/api/rest/comment.rs
- src/api/rest/gateway.rs
- src/api/rest/label.rs
- src/api/rest/section.rs
This adds the last few gateway unit tests so I can be sure that the right calls
are being made when going through the gateway.
> Implement last of the gateway unit tests

- README.md
- src/api/rest/gateway.rs
- src/command.rs
- src/config.rs
- src/tasks/list.rs
The list command has become incredibly versatile, so let's just make it the
default.
> Make list the default command

- src/labels/label.rs
Will do the full label list when interactively selecting labels.
> Show ID when selecting labels for deletion

- src/api/rest/gateway.rs
- src/api/rest/label.rs
- src/api/rest/project.rs
- src/command.rs
- src/labels/label.rs
- src/projects/add.rs
- src/projects/delete.rs
- src/projects/mod.rs
This adds project creation and deletion commands. Allows to set the name and use
the interactive list when deleting.
> Implement project creation and deletion

- src/api/rest/comment.rs
- src/api/rest/display.rs
- src/api/rest/label.rs
- src/api/rest/mod.rs
- src/api/rest/task.rs
This was just slightly annoying to handle so just moving to separate file and
fixing docs.
> Move all extra display items to own module

- src/api/tree.rs
- src/tasks/list.rs
- src/tasks/state.rs
It's a bit awkward when you see a task in the list without any further context
beside the project and labels. This adds an `--expand` parameter to the list
functionality to show the parents of the tasks that were part of the filter.
> Enable subtask parent expansion

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/lib.rs
- tests/commands/auth.rs
- tests/commands/main.rs
The first of many various integration tests, this checks if the authentication
is being correctly set up when doing `doist auth`.
> Add authentication integration test

- tests/commands/auth.rs
- tests/commands/list.rs
- tests/commands/main.rs
- tests/commands/setup.rs
Just wanted to get started with some initial tooling setup.
> Add first phase of list integration test

- src/tasks/create.rs
This will allow to select a project during interactive task creation. Next up
should be section selection.
> Implement project selection in interactive task creation

- src/tasks/create.rs
Now in addition to interactive project input, section input is also fully
dynamic.
> Full interactive section input

- Cargo.lock
- Cargo.toml
- src/command.rs
- src/interactive.rs
- src/labels/label.rs
- src/projects/list.rs
- src/tasks/add.rs
- src/tasks/close.rs
- src/tasks/edit.rs
- src/tasks/filter.rs
- src/tasks/list.rs
- src/tasks/priority.rs
Goes through the whole process of updating to the newest clap, and went through
all the deprecation warnings too.
> Upgrade to clap 4

- src/tasks/list.rs
- src/tasks/state.rs
Just minor code cleanup, preparing a bit for a deeper action menu that allows
filters etc.
> Interactive task code cleanup

- src/tasks/list.rs
- src/tasks/state.rs
Will be able to put other items into this submenu, like picking a new filter.
For now business as usual with the existing task creation.
> Refactor task creation menu into submenu

- src/tasks/filter.rs
- src/tasks/list.rs
Adds additional filters to the action menu. Tried cleaning it up a little, but
really don't want to go nightly. This is fine for now.
> Add more custom filters to action menu

- Cargo.lock
- Cargo.toml
- src/api/rest/gateway.rs
- Add retries and backoffs to the gateway, should make it just a tad more
resilient.
- Update cargo deps
> Add retries and backoffs

- src/command.rs
> Make list default for the label command

- tests/commands/list.rs
> Add tests for all variants of list

- src/tasks/state.rs
- tests/commands/fixtures/mod.rs
- tests/commands/fixtures/task_expand_output
- tests/commands/fixtures/tasks_partial.json
- tests/commands/list.rs
Test might be flaky? Need to investigate when I make a cleanup.
> Add integration test for list expand

- Cargo.lock
- Cargo.toml
Updating the cargo deps since we haven't had these for a while.
> Update cargo deps

- vhs/fixtures_server.py
- vhs/run_doist_fixtures.sh
Just some initial work to allow for vhs to run dummy commands on the cli. Might
be useful for further testing too.
> Add fixtures setup for vhs

- src/api/rest/task.rs
- src/api/sync/data.rs
New clippy detects, so we gotta make sure we implement it or our CI is gonna
scream.
> Fix clippy with default derives

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/labels/mod.rs
- src/tasks/filter.rs
Just wanted to update a few things so I have a nice base to make some
improvements here.
> Upgrade crates and run recent clippy

- .github/workflows/release.yml
- Cargo.toml
Going to use cargo-release right after this one to check if everything works as
expected.
> Set up cargo dist

- .github/workflows/release.yml
- dist-workspace.toml
Created a homebrew tap so it's possible to add doist via brew
> Enable homebrew tap when publishing

- Cargo.lock
- Cargo.toml
- src/api/rest/display.rs
- src/api/rest/gateway.rs
- src/api/tree.rs
- src/config.rs
- src/interactive.rs
- src/labels/delete.rs
- src/labels/label.rs
- src/projects/list.rs
- src/projects/state.rs
- src/projects/view.rs
- src/sections/list.rs
- src/tasks/add.rs
- src/tasks/close.rs
- src/tasks/create.rs
- src/tasks/edit.rs
- src/tasks/filter.rs
- src/tasks/list.rs
- src/tasks/state.rs
- src/tasks/view.rs
- tests/commands/mocks.rs
Upgrade to latest rust edition and pull in newest crate versions. Update some code accordingly.
> Use latest Rust edition

- .github/workflows/release.yml
- dist-workspace.toml
Manually picking ubuntu-latest was not compatible with cargo-dist. This fixes it by configuring cargo-dist.
> Use proper ubuntu assignment for cargo dist
