- Cargo.lock
- Cargo.toml
- src/api/rest/gateway.rs
- src/tasks/add.rs
Now you can use `doist add "something" -P Project` to assign a task easily to a project
> Allow assigning projects with fuzzy search on task add

- src/tasks/add.rs
- src/tasks/edit.rs
Due to some clap intricacies, the long name of a parameter is not set when
setting the short parameter name, so setting long parameter names explicitly for
the ones that need it.
Fixes #7.
> Add long and short params where applicable

- src/api/rest/gateway.rs
- src/tasks/add.rs
- src/tasks/edit.rs
- src/tasks/mod.rs
- src/tasks/section.rs
In addition to -P there will now also be -S which will select the section
instead of just the project. When a project is selected, then the section
selection will constrict itself to that project, but if used by itself with
enough uniqueness can assign even the project.
> Allow to set sections when adding tasks.

- src/api/rest/gateway.rs
- src/tasks/add.rs
- src/tasks/label.rs
- src/tasks/mod.rs
This adds the possibility to attach multiple labels when creating tasks via the
CLI. The fuzzy matching as with the other stuff applies, and it's possible to
attach multiple labels at once.
> Allow to add multiple labels when creating tasks.

- Cargo.lock
- Cargo.toml
- src/tasks/list.rs
I noticed that when updating to the latest dialoguer with the active element
theme, it does break existing colors in the selected item. This way I get the
old behavior back while perhaps contemplating a patch for dialoguer to unbreak
this.
> Force dialoguer theme for active item so it doesn't break colors

- src/api/rest/comment.rs
- src/api/rest/gateway.rs
- src/command.rs
- src/projects/comment.rs
- src/projects/mod.rs
- src/tasks/comment.rs
- src/tasks/mod.rs
Adds comment creation on projects and tasks. Additionally consolidated ID
handling on comments so it's either a task or a project and never both.
> ALlow to create comments on tasks and projects

- Cargo.lock
- Cargo.toml
- src/api/rest/label.rs
- src/api/rest/project.rs
This allows colors to assume other numbers that were not entirely documented by
the Todoist documentation. I assume this is helpful for older projects, but will
make it also resilient for future updates. Added a small test to make sure this
case is fixed.
Fixes #24.
> Fix undocumented colors crashing the app

- src/tasks/fuzz_select.rs
- src/tasks/label.rs
- src/tasks/list.rs
- src/tasks/project.rs
- src/tasks/section.rs
Added the various project, section and label filters to list, so in addition to
the default todoist filters, you can use the `doist` provided fuzzy matching
filters to display the list accordingly.
Improves #25 partway.
> Make list more powerful with more filters

- src/projects/list.rs
Adds a filter to `doist projects list` that then can be used to show how many
tasks a project has. If a project has 0 tasks, it is not displayed. Also added a
sneaky unit test.
Example usage is `doist projects list -f all`, but for example the regular list default of `doist projects list -f "(today | overdue)"` also works.
Fixes #25.
> Implement Project filter for `projects list`

- src/command.rs
- src/labels/list.rs
- src/labels/mod.rs
- src/lib.rs
Lists available labels using `doist labels list`. Will build out so labels can
be created and deleted (if possible through the API), but at least they're now
visible.
> Add labels list command

- src/api/rest/project.rs
- src/api/rest/task.rs
- src/api/tree.rs
If a parent task is not included in the current todoist filter, the app will
currently crash. This will essentially ignore the parents to ensure that the
list can still be reliably displayed without crashing, at the cost of not being
able to show the subtask relationship.
This is planned to improve by fetching _all_ tasks and then showing the subset
of tasks that were fetched via the filter, but that will come later.
Fixes #38
> Flatten the list if parent isn't in current filter

- src/interactive.rs
- src/projects/mod.rs
- src/projects/state.rs
- src/projects/view.rs
- src/tasks/filter.rs
- src/tasks/list.rs
- src/tasks/mod.rs
- src/tasks/state.rs
- src/tasks/view.rs
This makes it a bit easier to read. In particular moved tasks::list::List to
tasks::state::State and renamed the projects::filter::List to
projects::state::State
> Renamed the vague List to State for both Tasks and Projects

- src/labels/label.rs
- src/tasks/edit.rs
- src/tasks/list.rs
This will allow to add labels when editing tasks through the edit command.
Should eventually make this possible through the task list, but that requires a
bit more TLC.
> Add ability to add labels when editing tasks

- Cargo.lock
- Cargo.toml
- src/api/rest/display.rs
- src/api/rest/label.rs
- src/api/rest/project.rs
- src/api/rest/section.rs
- src/api/rest/task.rs
- src/tasks/close.rs
- src/tasks/list.rs
Color will only show in terminals that support it and when the environment
variable NO_COLOR is not set. This will make the output properly pipable.
> Adjust coloring to disable it when requested

- README.md
- src/tasks/list.rs
It was always kind of annoying that after every single operation `doist` had to
be restarted. Now with `doist -i` it is possible to keep closing/editing tasks
until `ESC` is pressed, thus making it a bit closer to the main app experience.
> Implement continuous interactive mode

- src/api/rest/task.rs
- src/command.rs
- src/tasks/add.rs
- src/tasks/create.rs
- src/tasks/mod.rs
This implements a first pass of the interactive task creation menu. Using `doist A` it's now possible to start creating a task fully interactively. Will expand this a bit later to allow adding labels and projects/sections.
> Add doist create for interactively creating a task

- src/interactive.rs
- src/tasks/create.rs
- src/tasks/list.rs
Adds filtering on top of creating tasks in interactive mode actions. A bit
verbose but gets the job done. Will potentially clean up later.
> Allow to set filter on interactive task list

- src/command.rs
Makes it easier to read the help.
> Make all aliases visible in help text

- src/bin/doist.rs
- src/command.rs
- src/lib.rs
This makes the API a tad bit easier to use. Will do the same with all other
listables.
> Make list the default when passing projects with argument

- src/command.rs
This concludes cleaning up of the command line. All commands can now be
expressed without the explicit list (though that one is still possible).
> Make list default for section command

- vhs/fixtures_server.py
- vhs/generate_vhs.sh
- vhs/intro.tape
- vhs/run_doist_fixtures.sh
While not complete yet, this fully enables at least read endpoints to be read
with the fixtures provided by the tests. VHS can already start generating some
gifs from that. Before this is completed, will still need adding tasks (at
least) and write a new VHS tape.
> Enable fixtures for reading all endpoints

- src/api/rest/project.rs
Small oversight, other REST API endpoints have already a signed order.
Fixes #90
> Fix projects not being able to have negative order

- tests/commands/list.rs
- tests/commands/mocks.rs
List expand was messing up the orders in the mock calls. Constricted the mock
call properly now.
> Fix flaky test

- README.md
- src/config.rs
- src/tasks/filter.rs
- src/tasks/list.rs
- tests/commands/setup.rs
This implements the ask in #95.
Now the filter will prioritize a passed-in argument, but on an empty argument,
it will fall back to the default filter, which is either declared in the config
file, or falling back even further to the in-code declared ``(today | upcoming)``
> Set default filter via configuration file

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
This updates cargo-dist to the latest and greatest, while also updating all
dependencies.
Dropping Windows support for now, as that just didn't vibe with the dependencies
I currently have on xdg paths.
> Update cargo-dist to latest

- src/api/rest/gateway.rs
This will make the editing commands properly work by parsing the response
correctly instead of failing to do so. The editing usually worked, but always
had the ugly error message popping out.
Fixes #99
> fix: editing will parse response correctly

- src/api/rest/label.rs
- src/api/rest/project.rs
- src/api/rest/task.rs
- src/tasks/add.rs
- src/tasks/edit.rs
Todoist API has changed to accept labels directly instead of label IDs. This PR
changes all occurences of label IDs to label names.
I also snuck in one extra API change, but it should not impact anything.
Fixes #111.
> Fix label API updates

- src/tasks/state.rs
- tests/commands/setup.rs
New rust versions added a few more default warnings, so the code needs a slight
update to compile properly.
> Clean up some warnings when compiling doist

- Cargo.lock
- Cargo.toml
- src/bin/doist.rs
- src/interactive.rs
This removes some of the default boilerplate error messages in the color-eyre result.
Additionally some cleanups in the various files affected.
> Clean up error output for error messages.

- src/api/rest/project.rs
Calendar type projects fail to parse without this.
> Add calendar project type.

- src/tasks/list.rs
This makes it a bit clearer what the individual things do in the task list. Closes #135
> Adjust wording for completing tasks
